import type { CargoPreset } from "@/types";
import { CARGO_COLORS } from "@/lib/constants";

/**
 * Встроенные пресеты грузов. Можно редактировать (override в сторе пресетов)
 * и сбрасывать; пользовательские добавляются рядом.
 */
export const BUILTIN_CARGO_PRESETS: CargoPreset[] = [
  {
    id: "cargo.box.s",
    name: "Коробка S (400×300×250)",
    nameEn: "Box S (400×300×250)",
    builtin: true,
    data: {
      name: "Коробка S",
      shape: "box",
      length: 400,
      width: 300,
      height: 250,
      diameter: 0,
      weight: 5,
      quantity: 1,
      stackable: true,
      maxTopLoad: 80,
      group: "general",
      color: CARGO_COLORS[0],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.box.m",
    name: "Коробка M (600×400×400)",
    nameEn: "Box M (600×400×400)",
    builtin: true,
    data: {
      name: "Коробка M",
      shape: "box",
      length: 600,
      width: 400,
      height: 400,
      diameter: 0,
      weight: 12,
      quantity: 1,
      stackable: true,
      maxTopLoad: 150,
      group: "general",
      color: CARGO_COLORS[4],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.box.l",
    name: "Коробка L (800×600×600)",
    nameEn: "Box L (800×600×600)",
    builtin: true,
    data: {
      name: "Коробка L",
      shape: "box",
      length: 800,
      width: 600,
      height: 600,
      diameter: 0,
      weight: 25,
      quantity: 1,
      stackable: true,
      maxTopLoad: 250,
      group: "general",
      color: CARGO_COLORS[8],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.box.appliance",
    name: "Упаковка техники (1200×600×800)",
    nameEn: "Appliance box (1200×600×800)",
    builtin: true,
    data: {
      name: "Упаковка техники",
      shape: "box",
      length: 1200,
      width: 600,
      height: 800,
      diameter: 0,
      weight: 40,
      quantity: 1,
      stackable: true,
      maxTopLoad: 120,
      group: "fragile",
      color: CARGO_COLORS[2],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.pallet.euro",
    name: "Европаллета (1200×800×1400)",
    nameEn: "Euro pallet (1200×800×1400)",
    builtin: true,
    data: {
      name: "Европаллета",
      shape: "box",
      length: 1200,
      width: 800,
      height: 1400,
      diameter: 0,
      weight: 650,
      quantity: 1,
      stackable: true,
      maxTopLoad: 400,
      group: "general",
      color: CARGO_COLORS[5],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.pallet.ind",
    name: "Промышленная паллета (1200×1000×1600)",
    nameEn: "Industrial pallet (1200×1000×1600)",
    builtin: true,
    data: {
      name: "Промпаллета",
      shape: "box",
      length: 1200,
      width: 1000,
      height: 1600,
      diameter: 0,
      weight: 800,
      quantity: 1,
      stackable: true,
      maxTopLoad: 300,
      group: "general",
      color: CARGO_COLORS[9],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.barrel.metal",
    name: "Бочка металлическая (Ø570×880)",
    nameEn: "Steel drum (Ø570×880)",
    builtin: true,
    data: {
      name: "Бочка металлическая",
      shape: "cylinder",
      length: 880,
      width: 570,
      height: 570,
      diameter: 570,
      weight: 220,
      quantity: 1,
      stackable: true,
      maxTopLoad: 350,
      group: "chemical",
      color: CARGO_COLORS[10],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.barrel.plastic",
    name: "Бочка пластиковая (Ø600×900)",
    nameEn: "Plastic drum (Ø600×900)",
    builtin: true,
    data: {
      name: "Бочка пластиковая",
      shape: "cylinder",
      length: 900,
      width: 600,
      height: 600,
      diameter: 600,
      weight: 180,
      quantity: 1,
      stackable: true,
      maxTopLoad: 200,
      group: "chemical",
      color: CARGO_COLORS[1],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.cylinder.gas",
    name: "Баллон газовый (Ø300×1500)",
    nameEn: "Gas cylinder (Ø300×1500)",
    builtin: true,
    data: {
      name: "Баллон газовый",
      shape: "cylinder",
      length: 1500,
      width: 300,
      height: 300,
      diameter: 300,
      weight: 60,
      quantity: 1,
      stackable: false,
      maxTopLoad: 0,
      group: "chemical",
      color: CARGO_COLORS[6],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.tire",
    name: "Колесо грузовое (Ø1000×320)",
    nameEn: "Truck tire (Ø1000×320)",
    builtin: true,
    data: {
      name: "Колесо грузовое",
      shape: "cylinder",
      length: 320,
      width: 1000,
      height: 1000,
      diameter: 1000,
      weight: 65,
      quantity: 1,
      stackable: true,
      maxTopLoad: 120,
      group: "general",
      color: CARGO_COLORS[11],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.bag.big",
    name: "Биг-бэг (900×900×1100)",
    nameEn: "Big bag (900×900×1100)",
    builtin: true,
    data: {
      name: "Биг-бэг",
      shape: "box",
      length: 900,
      width: 900,
      height: 1100,
      diameter: 0,
      weight: 400,
      quantity: 1,
      stackable: true,
      maxTopLoad: 100,
      group: "food",
      color: CARGO_COLORS[3],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.machine",
    name: "Станок негабаритный (2500×1500×2000)",
    nameEn: "Oversize machine (2500×1500×2000)",
    builtin: true,
    data: {
      name: "Станок",
      shape: "oversize",
      length: 2500,
      width: 1500,
      height: 2000,
      diameter: 0,
      weight: 1800,
      quantity: 1,
      stackable: false,
      maxTopLoad: 0,
      group: "machinery",
      color: CARGO_COLORS[7],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.metal.sheet",
    name: "Листы металлопроката (2000×1000×300)",
    nameEn: "Metal sheets (2000×1000×300)",
    builtin: true,
    data: {
      name: "Металлопрокат",
      shape: "box",
      length: 2000,
      width: 1000,
      height: 300,
      diameter: 0,
      weight: 900,
      quantity: 1,
      stackable: true,
      maxTopLoad: 4000,
      group: "metal",
      color: CARGO_COLORS[5],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
  {
    id: "cargo.roll",
    name: "Рулон бумаги (Ø1200×1100)",
    nameEn: "Paper roll (Ø1200×1100)",
    builtin: true,
    data: {
      name: "Рулон бумаги",
      shape: "cylinder",
      length: 1100,
      width: 1200,
      height: 1200,
      diameter: 1200,
      weight: 750,
      quantity: 1,
      stackable: true,
      maxTopLoad: 500,
      group: "general",
      color: CARGO_COLORS[8],
      cylinderAxis: "up",
      stopIndex: 0,
    },
  },
];
