import type { VehicleSpec } from "@/types";

/**
 * Встроенные пресеты транспорта. Габариты и оси — инженерные оценки
 * по типовым моделям (для расчёта осевых нагрузок позиции осей
 * заданы от передней стенки кузова; оси тягача — отрицательные).
 */
export const BUILTIN_VEHICLES: VehicleSpec[] = [
  {
    id: "vehicle.gazel",
    name: "ГАЗель",
    nameEn: "GAZel",
    builtin: true,
    innerLength: 3100,
    innerWidth: 1750,
    innerHeight: 1800,
    payload: 1500,
    tare: 2100,
    axleLayout: "rigid",
    axles: [
      { id: "axle.front", label: "Передняя", position: -900, maxLoad: 1500, tareShare: 0.55 },
      { id: "axle.rear", label: "Задняя", position: 2400, maxLoad: 2500, tareShare: 0.45 },
    ],
    loadingSides: ["rear", "right", "left", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Тент",
  },
  {
    id: "vehicle.bychok",
    name: "Бычок",
    nameEn: "Bychok",
    builtin: true,
    innerLength: 4200,
    innerWidth: 2100,
    innerHeight: 2000,
    payload: 3000,
    tare: 3600,
    axleLayout: "rigid",
    axles: [
      { id: "axle.front", label: "Передняя", position: -1300, maxLoad: 2500, tareShare: 0.5 },
      { id: "axle.rear", label: "Задняя", position: 3700, maxLoad: 4500, tareShare: 0.5 },
    ],
    loadingSides: ["rear", "right", "left", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Борт",
  },
  {
    id: "vehicle.zil",
    name: "ЗИЛ",
    nameEn: "ZIL",
    builtin: true,
    innerLength: 4500,
    innerWidth: 2300,
    innerHeight: 2300,
    payload: 4500,
    tare: 4400,
    axleLayout: "rigid",
    axles: [
      { id: "axle.front", label: "Передняя", position: -1500, maxLoad: 3500, tareShare: 0.48 },
      { id: "axle.rear", label: "Задняя", position: 4200, maxLoad: 7000, tareShare: 0.52 },
    ],
    loadingSides: ["rear", "right", "left", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Борт с тентом",
  },
  {
    id: "vehicle.kamaz",
    name: "КамАЗ",
    nameEn: "KamAZ",
    builtin: true,
    innerLength: 6200,
    innerWidth: 2450,
    innerHeight: 2500,
    payload: 10000,
    tare: 7600,
    axleLayout: "rigid",
    axles: [
      { id: "axle.front", label: "Передняя", position: -2000, maxLoad: 6000, tareShare: 0.4 },
      { id: "axle.drive1", label: "Ведущая 1", position: 4900, maxLoad: 8000, tareShare: 0.32 },
      { id: "axle.drive2", label: "Ведущая 2", position: 6200, maxLoad: 8000, tareShare: 0.28 },
    ],
    loadingSides: ["rear", "right", "left", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Борт с тентом",
  },
  {
    id: "vehicle.euro",
    name: "Еврофура",
    nameEn: "Euro truck",
    builtin: true,
    innerLength: 13600,
    innerWidth: 2450,
    innerHeight: 2700,
    payload: 20000,
    tare: 14500,
    axleLayout: "tractor-semi",
    axles: [
      { id: "axle.steer", label: "Тягач, рулевая", position: -5100, maxLoad: 7000, tareShare: 0.2 },
      { id: "axle.drive", label: "Тягач, ведущая", position: -2600, maxLoad: 11500, tareShare: 0.33 },
      { id: "axle.tr1", label: "Прицеп, 1", position: 12600, maxLoad: 10000, tareShare: 0.16 },
      { id: "axle.tr2", label: "Прицеп, 2", position: 13150, maxLoad: 10000, tareShare: 0.155 },
      { id: "axle.tr3", label: "Прицеп, 3", position: 13700, maxLoad: 10000, tareShare: 0.155 },
    ],
    loadingSides: ["rear", "right", "left"],
    defaultLoadingSide: "rear",
    bodyType: "Тент / полуприцеп",
  },
  {
    id: "vehicle.jumbo",
    name: "Jumbo",
    nameEn: "Jumbo",
    builtin: true,
    innerLength: 13600,
    innerWidth: 2480,
    innerHeight: 3000,
    payload: 24000,
    tare: 15500,
    axleLayout: "tractor-semi",
    axles: [
      { id: "axle.steer", label: "Тягач, рулевая", position: -5100, maxLoad: 7000, tareShare: 0.19 },
      { id: "axle.drive", label: "Тягач, ведущая", position: -2600, maxLoad: 11500, tareShare: 0.34 },
      { id: "axle.tr1", label: "Прицеп, 1", position: 12600, maxLoad: 10000, tareShare: 0.16 },
      { id: "axle.tr2", label: "Прицеп, 2", position: 13150, maxLoad: 10000, tareShare: 0.155 },
      { id: "axle.tr3", label: "Прицеп, 3", position: 13700, maxLoad: 10000, tareShare: 0.155 },
    ],
    loadingSides: ["rear", "right", "left", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Низкорамный тент (мега)",
  },
  {
    id: "vehicle.reefer",
    name: "Рефрижератор",
    nameEn: "Refrigerated truck",
    builtin: true,
    innerLength: 7800,
    innerWidth: 2400,
    innerHeight: 2450,
    payload: 8000,
    tare: 7200,
    axleLayout: "rigid",
    axles: [
      { id: "axle.front", label: "Передняя", position: -1700, maxLoad: 5500, tareShare: 0.42 },
      { id: "axle.rear", label: "Задняя", position: 7400, maxLoad: 10000, tareShare: 0.58 },
    ],
    loadingSides: ["rear", "top"],
    defaultLoadingSide: "rear",
    bodyType: "Изотермический кузов",
  },
];
